# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(unique=True, verbose_name='url'),
        ),
    ]
